import * as THREE from 'three';
import { useEffect } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export default function Macbook(props) {
  const { nodes, materials } = useGLTF('/models/macbook.glb');

  const texture = useTexture(props.item.img);

  useEffect(() => {
    Object.entries(materials).map((material) => {
      console.log(material[0]);
      //   these are the material names that can't be changed color
      if (material[0] !== 'IRmQBwmazXillxR') {
        material[1].color = new THREE.Color(props.item.color[0]);
        console.log(props.item.color[0]);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props.item]);

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AbUSUIrCaeUDCsJ.geometry}
          material={materials.wgigXEahTjNNjwA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AvyykvDoWBuLcEN.geometry}
          material={materials.ViHztBofDGslDJK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.aWITVlDgwVQtoKH.geometry}
          material={materials.udoWhfCARevRdfj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body.geometry}
          material={materials.lqJBugNJnTxrFNq}
        />
        <meshStandardMaterial roughness={1} map={texture} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bottom.geometry}
          material={materials.WHyvFUEiMyWSHPp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BZjmwPQQTPcmKaw.geometry}
          material={materials.RMZVuCquSSFOZvO}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DfdIaEUTFhXrCZh.geometry}
          material={materials.gXnYgKPeKcdKxGx}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DzsUpYYoOIiYsUP.geometry}
          material={materials.fSdnqvHpIKeCQyV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.eogaOJZVOtgLTzk.geometry}
          material={materials.ESNYmHoIfpJIXaw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EOLaNwsnWHeUowg.geometry}
          material={materials.OyStturqsrbCyIN}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.feRmjpVaeLEuLct.geometry}
          material={materials.qaTCRmQMQgqIFUF}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HLklavDSMzGVgpv.geometry}
          material={materials.jrqhXBmqAJJvbba}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hOXcXlqYtezucxq.geometry}
          material={materials.IRmQBwmazXillxR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IOEnlSHZXYVoPvZ.geometry}
          material={materials.neWMvlnzbEhydxP}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jzAbEcSYuyYzDTW.geometry}
          material={materials.QpaZDirVCuzVLSB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.keyboard.geometry}
          material={materials.IRmQBwmazXillxR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leftspeaker.geometry}
          material={materials.MHbGibFlvsfvUjq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MJCsCDYctXzJOrv_0.geometry}
          material={materials.LJXvFXkckZWZSAJ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MmNOFkillydkUUA.geometry}
          material={materials.tqdmvmpNZJVxyrd}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.name.geometry}
          material={materials.XKxFFtHkILdcigV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nXFCVlKUPkwzMyX.geometry}
          material={materials.ManCKkRmKAhOkEC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.oSkMufEEaEikrda.geometry}
          material={materials.ESNYmHoIfpJIXaw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OVleACBbjalqKNy.geometry}
          material={materials.qaTCRmQMQgqIFUF}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pbcjkgIILSHRUPg.geometry}
          material={materials.WHyvFUEiMyWSHPp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PQbepcKuJtVJvcO.geometry}
          material={materials.wsjsgEUyvhzwsFT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rightspeaker.geometry}
          material={materials.MHbGibFlvsfvUjq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RmUlpDRcbYvxvMG.geometry}
          material={materials.qwkFSFQNMBwguPQ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rYmggbWaAoNvkWb.geometry}
          material={materials.lmkNrKQLQzPeiPo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rZhxrtaanbUKXXT.geometry}
          material={materials.VoDYoGHenLMtHYN}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tEKCZmhUgLIlmiW.geometry}
          material={materials.jiXyBrRnsQaOfPi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TmOTUhXtKEUrkPf.geometry}
          material={materials.FgXymxmBfJBhPlB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TqcLBYEWEqrBeHf.geometry}
          material={materials.ewSGvlxhvDgapcl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trackpad.geometry}
          material={materials.zlrKiEYuykraeAj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TumtbkEqWoVcjVW.geometry}
          material={materials.PcASCxFQlsRQYBv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XgTmruRSYPrTodJ.geometry}
          material={materials.tqdmvmpNZJVxyrd}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XIBxqEKdSHMvFxO.geometry}
          material={materials.VfkdCyLQUYSyjiY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZKPKdYNcjUxVtCX.geometry}
          material={materials.QpaZDirVCuzVLSB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cap.geometry}
          material={materials.ifbRUXQxBkiUWZG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GvOwFLrWTuGoVYz.geometry}
          material={materials.udoWhfCARevRdfj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GZRvSPNppBjJorn.geometry}
          material={materials.fVCKZnaMRlyopPL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.logo.geometry}
          material={materials.ZiVQlSjqCcltQCJ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LzqakmqpbXdgbVr.geometry}
          material={materials.tqdmvmpNZJVxyrd}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pYASezxyPGyTvVM.geometry}
          material={materials.QWTijDAGbCwrOWg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pyGXtbRuyHzlLeb.geometry}
          material={materials.oowSJBdGgkjQYIM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.qjSRMkXvocsPboT.geometry}
          material={materials.hvBjBDBHERtlkxy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.screen.geometry}
          material={materials.qkZOLUHiVYgMckg}
        />
        <meshStandardMaterial roughness={1} map={texture} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.seUvIwDesGFJNcE.geometry}
          material={materials.ESNYmHoIfpJIXaw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.YIQWIEmpwzXKNga.geometry}
          material={materials.ifbRUXQxBkiUWZG}
        />
      </group>
    </group>
  );
}

useGLTF.preload('models/macbook.glb');
